### GET
GET http://localhost:3000/tasks 


### POST 
POST http://localhost:3000/tasks/new
content-Type: application/json 

{
"title": "Active Mission",
"dueDate": "2026-03-20"
}


### PATCH 
PATCH http://localhost:3000/tasks/complete/2


### PATCH
PATCH http://localhost:3000/tasks/incomplete/3 


### DELETE
DELETE http://localhost:3000/tasks/delete/4


### PUT 
PUT http://localhost:3000/tasks/edit/2
content-Type: application/json

{
"title": "Find the lost treasure",
"dueDate": "2025-07-23"
}

 

